server:
  port: 8091

spring:
  profiles:
    active: path_route
  application:
    name: service-gateway


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/



# 根据服务名路由
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 开启服务注册和发现的功能
          # gateway自动根据服务发现为每一个服务创建了一个router,
          # 这个router将以服务名开头的请求路径转发到对应的服务
          enabled: true
          # 将请求路径上的服务名配置为小写
          lowerCaseServiceId: true
  profiles: service_name_route


## 根据特定的前缀把请求路由到对应的服务
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: service-a
        # 服务的负载均衡地址
        uri: lb://SERVICE-A
        predicates:
          - Path=/demo/**
        filters:
          # StripPrefix的filter在转发之前将/demo去掉
          - StripPrefix=1
  profiles: path_route
